server:
  port: 8506
  
spring:
  application:
    name: spring-cloud-sleuth-product
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 注册到 consul 的服务名称
        serviceName: sleuth-product-service

  zipkin:
    base-url: http://localhost:9411/
    service:
      name: sleuth-product
