server:
  port: 8503
  
spring:
  application:
    name: spring-cloud-sleuth-store
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 注册到 consul 的服务名称
        serviceName: sleuth-store-service

  zipkin:
    base-url: http://localhost:9411/
    service:
      name: sleuth-store
