server:
  port: 8501
  
spring:
  application:
    name: spring-cloud-sleuth-query
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 设置不需要注册到 consul 中
        register: false

  zipkin:
    base-url: http://localhost:9411/
    service:
      name: sleuth-query
